---
apiVersion: v1
kind: Namespace
metadata:
  name: valkyrie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app
  namespace: valkyrie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: critical-app
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      containers:
      - name: critical-app
        image: registry.localhost:5000/valkyrie-app:1.4
        ports:
        - containerPort: 8080

        # Startup Probe - Determines when the application has successfully started
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - "test -f /tmp/startup-file"  # Checks if a file exists to indicate startup completion
          initialDelaySeconds: 10  # How long to wait before running the first probe check
          periodSeconds: 10        # How often (in seconds) to perform the probe
          timeoutSeconds: 10       # Number of seconds after which the probe times out
          failureThreshold: 5     # How many times the probe can fail before the pod is marked as Unhealthy
          successThreshold: 1      # Minimum number of consecutive successes before marking the container as started. For startup probes, this is set to 1.
          terminationGracePeriodSeconds: 30  # Time to wait before forcefully terminating the container if it doesn't start in time

        # Liveness Probe - Determines if the application is still running
        livenessProbe:
          httpGet:
            path: /liveness-health  # Calls this endpoint to check if the app is alive
            port: 8080
          initialDelaySeconds: 10  # How long to wait before running the first probe check
          periodSeconds: 10        # How often (in seconds) to perform the probe
          timeoutSeconds: 10       # Number of seconds after which the probe times out
          failureThreshold: 5     # How many times the probe can fail before the pod is marked as Unhealthy
          successThreshold: 1      # Minimum number of consecutive successes before marking the container as started. For liveness probes, this is set to 1.
          terminationGracePeriodSeconds: 30  # Time to wait before forcefully terminating the container if it doesn't respond in time

        # Readiness Probe - Determines if the application is ready to receive traffic
        readinessProbe:
          httpGet:
            path: /readiness-health  # Calls this endpoint to check if the app is ready
            port: 8080
          initialDelaySeconds: 10  # How long to wait before running the first probe check
          periodSeconds: 10        # How often (in seconds) to perform the probe
          timeoutSeconds: 10       # Number of seconds after which the probe times out
          failureThreshold: 5     # How many times the probe can fail before the pod is marked as Unhealthy
          successThreshold: 2      # Minimum number of consecutive successes before marking the container as started. For readiness probes, this can be set to x, where x is the number of times you want to ensure the app is ready before accepting traffic.
        env:
        - name: PRIME_NUMBER_COUNT
          value: "1000000"  # Environment variable to control the number of prime numbers to calculate. This will increase the startup time of the application.
---
# ClusterIP Service - Exposes the application within the cluster
apiVersion: v1
kind: Service
metadata:
  name: critical-app-clusterip
  namespace: valkyrie
spec:
  selector:
    app: critical-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valkyrie-ingress
  namespace: valkyrie
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: valkyrie.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: critical-app-clusterip
            port:
              number: 80
