apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app
  namespace: supera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: critical-app
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      containers:
      - name: critical-app
        image: supera/k8s-probe-test-valkyrie:1.1.1-lime
        ports:
        - containerPort: 8080
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - "test -f /tmp/startup-file"
          initialDelaySeconds: 10
          periodSeconds: 10   # How often (in seconds) to perform the probe.
          timeoutSeconds: 1   # Number of seconds after which the probe times out.
          failureThreshold: 5 # How many times the probe can fail before the pod is marked as Unhealthy
          successThreshold: 1 # Minimum consecutive successes for the probe to be considered successful
        livenessProbe:
          httpGet:
            path: /liveness-health
            port: 8080
          initialDelaySeconds: 10 # How long to wait before running the probe
          periodSeconds: 5    # How often (in seconds) to perform the probe.
          timeoutSeconds: 2   # Number of seconds after which the probe times out.
          successThreshold: 1 # Default and recommended for liveness
          failureThreshold: 3 # Determines how many times the probe must fail to mark the pod as Unhealthy
        readinessProbe:
          tcpSocket: # Check if the port is open
            port: 8080
          initialDelaySeconds: 10 # How long to wait before running the probe
          periodSeconds: 5     # How often (in seconds) to perform the probe.
          timeoutSeconds: 2   # Number of seconds after which the probe times out.
          successThreshold: 1 # Typically 1 for readiness to mark the pod as Ready after being successful once
          failureThreshold: 3 # How many times the probe can fail before the pod is marked as Unready
---
# clusterip service
apiVersion: v1
kind: Service
metadata:
  name: critical-app-clusterip
  namespace: supera
spec:
  selector:
    app: critical-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
